name: bmad-godot-game-dev
version: 1.0.0
short-title: Godot Game Dev Pack
description: Game Development expansion pack for BMad Method - Godot GDscript & C# focused
author: sjennings (Lum), based on BMAD Unity Game Dev expansion pack by pbean (PinkyD)
slashPrefix: BmadG
markdownExploder: true
qa:
  qaLocation: docs/qa
prd:
  prdFile: docs/game-prd.md
  prdVersion: v0.2
  prdSharded: false
  prdShardedLocation: null
  epicFilePattern: epic-{n}*.md
architecture:
  architectureFile: docs/architecture.md
  architectureVersion: v0.1
  architectureSharded: false
  architectureShardedLocation: null
customTechnicalDocuments: null
devLoadAlwaysFiles:
  - docs/architecture.md
qaLoadAlwaysFiles:
  - docs/architecture.md
devDebugLog: .ai/debug-log.md
devStoryLocation: docs/stories
